name: Innotimer
favicon: null
layout_spectrum: 0.66927
typography_spectrum: 0.48807
title: Innotimer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7e7e7e'
    - '#ff7f22'
    - '#c3c3c3'
    - '#ffb882'
  brandStrength: 0.625
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
